# Generated by Django 2.0 on 2018-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='s_duration',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
